### PR TITLE
Pinned posts

### PR DESCRIPTION
**Pull request by petrkucerak**

### CODE REVIEW

**Comment by filiptronicek** [comment]
I love it, very well done and good looking on the desktop!
image

**Review by filiptronicek — DISMISSED** [review]
LGTM

**Comment by Vilican** [comment]
@petrkucerak, @filiptronicek - Nobody is really going to notice just a small pin in the corner. Also, have you confirmed the design with @Elesaa?

**Comment by filiptronicek** [comment]
Well, is it really to be so noticeable @Vilican? I don't think that it should stand out so much (would be very distracting.). The fact it's always the top article makes the user notice it more without any distractions.

**Comment by Elesaa** [comment]
Depends on how it looks with the other articles. Is it seperated from them reasonably? If so, the pin icon is fine, however what about marking it with some title such as “Článek týdne”.

**Comment by filiptronicek** [comment]
@Elesaa for now there is no spacing between the pinned post(s) and the other content, but we can give the pinned post a margin (this is `margin-bottom: 100px;`)
image

**Review by filiptronicek — APPROVED** [review]
LGTM

**Pull request merged**
