### PR TITLE
Setup GitPod

### PR DESCRIPTION
**Pull request by filiptronicek**
Add auto GitPod setup

### CODE REVIEW

**Comment by Vilican** [comment]
@filiptronicek - Our PHP parameters are as follows:

PHP memory_limit: 256 MB
PHP upload_max_filesize: 100 MB
PHP post_max_size: 100 MB
PHP max_execution_time: 90 s

It would be best to test code with them too.

**Comment by filiptronicek** [comment]
- [x] create an issue on GitPod setup WordPress 
- [ ] create GH action to transpile SCSS

**Comment by filiptronicek** [comment]
Errror when transpiling to CSS 
```bash
Compilation Error
Error: $string: ms-fadeIn  is not a string.
    ╷
177 │     $namelist: append($namelist, unquote($newname), 'comma');
    │                                  ^^^^^^^^^^^^^^^^^
    ╵
  /workspace/stcblog/assets/scss/fabric/mixins/_Animation.Mixins.MDL2.scss 177:34  ms-animation()
  /workspace/stcblog/assets/scss/fabric/mixins/_Animation.Mixins.MDL2.scss 205:5   @content
  /workspace/stcblog/assets/scss/fabric/mixins/_Directionality.Mixins.scss 11:5    ms-LTR()
  /workspace/stcblog/assets/scss/fabric/mixins/_Animation.Mixins.MDL2.scss 204:3   ms-slideRightIn10()
  /workspace/stcblog/assets/scss/fabric/_Animation.MDL2.scss 10:3                  @import
  /workspace/stcblog/assets/scss/fabric/_Animation.scss 58:9                       @import
  /workspace/stcblog/assets/scss/fabric/_Fabric.scss 12:9                          @import
  /workspace/stcblog/assets/scss/style.scss 18:9                                   root stylesheet
```

**Comment by filiptronicek** [comment]
Works, ready to merge

**Review by petrkucerak — APPROVED** [review]

**Pull request merged**
