### PR TITLE
Campaign banner 2021

### LINKED ISSUE #81: Banner with invitation to STC 2021
image

### PR DESCRIPTION
**Pull request by petrkucerak**

### CODE REVIEW

**Comment by Vilican** [comment]
@petrkucerak - Beware that JS files are cached for a long time (in case we'll need to update the ending date).

**Comment by petrkucerak** [comment]
@Vilican or @filiptronicek, please check the code.
The graphic has been approved by Anna Suruvkova.

**Review by filiptronicek — CHANGES_REQUESTED** [review]
Looks good, but there should be a safe area for the action button, otherwise, LGTM, wonderful job with the gradient!
8080-copper-trout-nuo1jngs ws-eu16 gitpod io_

**Comment by filiptronicek** [comment]
Working on rewriting the styles in flexbox...

**Review by filiptronicek — APPROVED** [review]

**Comment by petrkucerak** [comment]
@Vilican please check and approve the pull request.

**Review by Vilican — CHANGES_REQUESTED** [review]
@petrkucerak - Please see private chat in Teams.

**Review by Vilican — APPROVED** [review]

**Pull request merged**
