### PR TITLE
Enables auto-updating copyright year in the footer

### LINKED ISSUE #107: Auto update copyright date in footer

### PR DESCRIPTION
**Pull request by petrkucerak**

### CODE REVIEW

**Comment by petrkucerak** [comment]
The pull request is completed, please approve it @Vilican.

**Review by Vilican — CHANGES_REQUESTED** [review]
The copyright structure is as follows: `© 2019 – 2023 STC, Všechna práva vyhrazena`
This PR also contains changes from #109

**Comment by petrkucerak** [comment]
I changed the copyright structure to your requirement, @Vilican.

**Review by Vilican — APPROVED** [review]

**Comment by Vilican** [comment]
@petrkucerak - Approved. Just note that you have the edits from #109 here too.

**Pull request merged**
