### PR TITLE
Corrected the bad campaign date

### LINKED ISSUE #81: Banner with invitation to STC 2021
image

### PR DESCRIPTION
**Pull request by petrkucerak**

### CODE REVIEW

**Review by Vilican — CHANGES_REQUESTED** [review]
Cachebuster missing: JS files may be cached by client browsers for up to a year.

**Comment by Vilican** [comment]
@petrkucerak - This cachebuster technique prevents caching at all, which is not really wanted. I can look into this once I get back in my office.

**Comment by petrkucerak** [comment]
@Vilican any update?

**Review by Vilican — APPROVED** [review]
@petrkucerak - Oh, I must have missed the $version variable because I initially thought the appended query string would be random (from the "rnd" key). My bad, it's okay as it is.

**Pull request merged**
