### PR TITLE
Advent event

### PR DESCRIPTION
**Pull request by petrkucerak**

### CODE REVIEW

**Comment by petrkucerak** [comment]
_The quick status of progress_

image
image
image
image

**Comment by petrkucerak** [comment]
# ToDo:

## Globalni
- [x] banner na uvodni stranku

## Clanky
- [x] vlastni styl
- [x] tlacitko k navratu - banner

## Kalendar
- [x] odkazy + vypublikovani
- [x] aktualizace textu
- [x] zdroje a podminky fungovani
- [x] responzivita

## Jine
- [ ] vokomentovat kod + popsat zmeny do dokumentace!!!!

**Comment by petrkucerak** [comment]
image
image

**Comment by petrkucerak** [comment]
image

**Comment by petrkucerak** [comment]
image
image

**Comment by petrkucerak** [comment]
image

**Comment by petrkucerak** [comment]
image
image
image

**Comment by petrkucerak** [comment]
@filiptronicek @Vilican check the proposed changes, please.

**Review by filiptronicek — CHANGES_REQUESTED** [review]
Spectacular changes, @petrkucerak! Had one thing so far:
The contrast on this button is a no-go. It is barely visible and the appealing design of it is not very pronounced with this background. I suggest we either add some backdrop or change this button to a more generic contrasting color.
image

**Review by Vilican — CHANGES_REQUESTED** [review]
Same request as already @filiptronicek mentioned.
+ What happened to diacritics in the button?

**Comment by petrkucerak** [comment]
image
What about now, @Vilican @filiptronicek? I added some depth.

**Comment by petrkucerak** [comment]
image

**Review by filiptronicek — COMMENTED** [review]
@petrkucerak the button looks good to me.

**Comment by petrkucerak** [comment]
@filiptronicek some other changes?

**Review by Vilican — DISMISSED** [review]

**Review by filiptronicek — APPROVED** [review]
LGTM ✅

**Review by Vilican — APPROVED** [review]

**Pull request merged**
